# Generated by Django 2.1 on 2020-05-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name_plural': 'Dashboard Users'},
        ),
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name_plural': 'App Users'},
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='user_role',
            field=models.CharField(choices=[('SA', 'Super Admin'), ('A', 'Admin'), ('M', 'Manager'), ('S', 'Supervisor')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
