# Generated by Django 2.1 on 2020-05-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
