# Generated by Django 2.1 on 2020-05-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200522_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='full_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
