# Generated by Django 2.1 on 2020-06-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
