# Generated by Django 3.0 on 2020-06-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200613_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='ip',
            new_name='first_ip',
        ),
        migrations.AddField(
            model_name='appuser',
            name='ip_sign_in_today',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='login_via',
            field=models.CharField(choices=[('F', 'Facebook'), ('G', 'Google'), ('N', 'None')], default='N', max_length=2),
        ),
    ]
