# Generated by Django 3.0 on 2020-06-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200617_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_visible', models.BooleanField(default=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('website_visible', models.BooleanField(default=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_visible', models.BooleanField(default=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_visible', models.BooleanField(default=True)),
                ('instgram', models.CharField(blank=True, max_length=50, null=True)),
                ('instgram_visible', models.BooleanField(default=True)),
                ('gmail', models.CharField(blank=True, max_length=50, null=True)),
                ('gmail_visible', models.BooleanField(default=True)),
                ('youtube', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube_visible', models.BooleanField(default=True)),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_visible', models.BooleanField(default=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_visible', models.BooleanField(default=True)),
                ('snapchat', models.CharField(blank=True, max_length=50, null=True)),
                ('snapchat_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
