# Generated by Django 3.0 on 2020-06-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_appuser_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='friends_list',
            field=models.ManyToManyField(blank=True, related_name='friends', to='users.AppUser'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='status_list',
            field=models.ManyToManyField(blank=True, related_name='waiting_list', to='users.AppUser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
